Nom. : : 
Nom.: SendaConvert
version.: 1.0.0+1
Publier_to.: Aucun.

Environnement.:
 SDK. : '>=3.2.0 <4.0.0'

Dépendances.:
 Flutter. :
 SDK. : Flutter.

dev_dependances.:
 Flutter_test. :
 SDK. : Flutter.

Flutter.:
  Utilisations-matériel-conception. : true
